"""add thumbnail_url to resources

Revision ID: 8ffcbc43c71b
Revises: 975d2d851ddf
Create Date: 2026-07-08 21:06:25.302523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffcbc43c71b'
down_revision: Union[str, Sequence[str], None] = '975d2d851ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'thumbnail_url')
    # ### end Alembic commands ###
