"""task creator_id/owner_id survive account deletion (SET NULL)

Revision ID: 975d2d851ddf
Revises: a56cc6aef0e2
Create Date: 2026-07-08 00:23:54.912013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975d2d851ddf'
down_revision: Union[str, Sequence[str], None] = 'a56cc6aef0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('tasks_creator_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_owner_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_owner_id_fkey'), 'tasks', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('tasks_creator_id_fkey'), 'tasks', 'users', ['creator_id'], ['id'])
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
