"""workspace creator_id survives account deletion (SET NULL, no privileges tied to it)

Revision ID: a56cc6aef0e2
Revises: 2d35fdd3715a
Create Date: 2026-07-07 20:42:55.859878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56cc6aef0e2'
down_revision: Union[str, Sequence[str], None] = '2d35fdd3715a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('workspaces_creator_id_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_creator_id_fkey'), 'workspaces', 'users', ['creator_id'], ['id'])
    op.alter_column('workspaces', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
