"""add_workspace_is_completed_completed_at

Revision ID: f91496a3aeba
Revises: 59069898ae4c
Create Date: 2026-06-30 21:08:32.935455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91496a3aeba'
down_revision: Union[str, Sequence[str], None] = '59069898ae4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'completed_at')
    op.drop_column('workspaces', 'is_completed')
    # ### end Alembic commands ###
